// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGWBZmJ9a5EoLX45ptxpigmJFhwJR1_w4',
    appId: '1:371518018708:web:5125ff1da04a046ca31081',
    messagingSenderId: '371518018708',
    projectId: 'fir-app-f8514',
    authDomain: 'fir-app-f8514.firebaseapp.com',
    storageBucket: 'fir-app-f8514.firebasestorage.app',
    measurementId: 'G-D1JVZ9RJEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmhvYCiqQx2xo_nTOqeL4AKLbMjZd0ODg',
    appId: '1:371518018708:android:c7ac2c2941b6410ca31081',
    messagingSenderId: '371518018708',
    projectId: 'fir-app-f8514',
    storageBucket: 'fir-app-f8514.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqIgALZF3_4voLG2ffXHsUMtobjtTiOqs',
    appId: '1:371518018708:ios:f88a3a8875f2d012a31081',
    messagingSenderId: '371518018708',
    projectId: 'fir-app-f8514',
    storageBucket: 'fir-app-f8514.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqIgALZF3_4voLG2ffXHsUMtobjtTiOqs',
    appId: '1:371518018708:ios:f88a3a8875f2d012a31081',
    messagingSenderId: '371518018708',
    projectId: 'fir-app-f8514',
    storageBucket: 'fir-app-f8514.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGWBZmJ9a5EoLX45ptxpigmJFhwJR1_w4',
    appId: '1:371518018708:web:e9015ef56e8d07ada31081',
    messagingSenderId: '371518018708',
    projectId: 'fir-app-f8514',
    authDomain: 'fir-app-f8514.firebaseapp.com',
    storageBucket: 'fir-app-f8514.firebasestorage.app',
    measurementId: 'G-QGE9Z0EVY7',
  );
}
